export type ToolCategory = "create" | "server" | "optimize";
export type ToolStatus = "live" | "beta" | "new" | "coming_soon" | "maintenance";

export interface ToolDefinition {
  slug: string;
  name: string;
  category: ToolCategory;
  description: string;
  longDescription: string;
  icon: string; // lucide icon name
  /** Default credit cost (overridable in DB ToolConfig) */
  creditCost: number;
  status: ToolStatus;
  requiresAuth: boolean;
  requiresSubscription: boolean;
  requiresVerification: boolean;
  freeDailyExports?: number;
  accepts: string[]; // file extensions
  outputs: string[];
  processor: string;
  href: string;
}

export const TOOLS: ToolDefinition[] = [
  {
    slug: "prop-creator",
    name: "Prop Creator",
    category: "create",
    description: "Turn OBJ, FBX, glTF or DAE models into drag-and-drop FiveM props with collision, LODs and a spawn script.",
    longDescription: "Upload a model, position it against a 1.83m ped reference, pick collision and LOD settings, assign PBR textures, then export a complete streaming resource.",
    icon: "Box",
    creditCost: 40,
    status: "live",
    requiresAuth: true,
    requiresSubscription: false,
    requiresVerification: false,
    accepts: [".obj", ".fbx", ".gltf", ".glb", ".dae", ".mtl", ".png", ".jpg", ".jpeg", ".dds", ".zip"],
    outputs: [".ydr", ".ytyp", ".ytd", "fxmanifest.lua", "spawn script", "ZIP"],
    processor: "prop",
    href: "/app/tools/prop-creator",
  },
  {
    slug: "ai-prop-creator",
    name: "AI Prop Creator",
    category: "create",
    description: "Generate a textured 3D prop from a single image, then finish it in the Prop Creator.",
    longDescription: "One photo in, a PBR-textured mesh out. AI replaces only the modeling stage — the result opens in the same editor and export pipeline as any uploaded model.",
    icon: "Sparkles",
    creditCost: 120,
    status: "beta",
    requiresAuth: true,
    requiresSubscription: false,
    requiresVerification: true,
    accepts: [".png", ".jpg", ".jpeg", ".webp"],
    outputs: ["GLB", "PBR textures", "Prop resource"],
    processor: "ai-prop",
    href: "/app/tools/ai-prop-creator",
  },
  {
    slug: "car-importer",
    name: "Add-on Car Importer",
    category: "create",
    description: "Paste a GTA5-Mods link and receive a ready-to-stream add-on vehicle resource with audio and metadata intact.",
    longDescription: "Fetches the mod archive, detects DLC structure, converts replace mods into standalone add-ons, preserves engine audio and rewrites vehicle metadata.",
    icon: "Car",
    creditCost: 60,
    status: "live",
    requiresAuth: true,
    requiresSubscription: false,
    requiresVerification: false,
    accepts: ["gta5-mods.com URL", ".zip", ".rar", ".7z", ".oiv"],
    outputs: ["fxmanifest.lua", "vehicles.meta", "handling.meta", "carcols", "carvariations", "audio", "ZIP"],
    processor: "car-importer",
    href: "/app/tools/car-importer",
  },
  {
    slug: "vehicle-editor",
    name: "Vehicle Editor",
    category: "create",
    description: "Debadge, detrim, swap wheels, tune stance and re-export unlocked add-on vehicles in 3D.",
    longDescription: "Inspect every component of an unlocked add-on vehicle, hide or remove parts, adjust bodykits, wheels, stance and glowing trim, resize textures and tune LODs.",
    icon: "Wrench",
    creditCost: 50,
    status: "live",
    requiresAuth: true,
    requiresSubscription: false,
    requiresVerification: false,
    accepts: [".yft", ".ytd", ".zip"],
    outputs: ["Vehicle resource ZIP"],
    processor: "vehicle",
    href: "/app/tools/vehicle-editor",
  },
  {
    slug: "livery-mapper",
    name: "Livery Mapper",
    category: "create",
    description: "Design liveries on the car's real UV layout with a 2D canvas and live 3D preview.",
    longDescription: "Layer images, logos, text and shapes on the vehicle's actual UV template and bake the design into the vehicle texture — no native livery slot required.",
    icon: "Palette",
    creditCost: 35,
    status: "live",
    requiresAuth: true,
    requiresSubscription: false,
    requiresVerification: false,
    accepts: [".yft", ".ytd", ".zip", ".png", ".jpg"],
    outputs: ["Patched vehicle", "textures", "fxmanifest.lua", "ZIP"],
    processor: "livery",
    href: "/app/tools/livery-mapper",
  },
  {
    slug: "retexture",
    name: "Retexture",
    category: "create",
    description: "Click any surface of a prop, MLO or vehicle and swap its texture.",
    longDescription: "Load a resource, pick a surface in 3D to identify its material and texture, upload a replacement, crop, scale, fit and colour-adjust, then rebuild the resource.",
    icon: "Layers",
    creditCost: 30,
    status: "live",
    requiresAuth: true,
    requiresSubscription: false,
    requiresVerification: false,
    accepts: [".ydr", ".yft", ".ytd", ".zip", ".png", ".jpg", ".dds"],
    outputs: ["Rebuilt resource ZIP"],
    processor: "retexture",
    href: "/app/tools/retexture",
  },
  {
    slug: "clothing-textures",
    name: "Clothing Textures",
    category: "create",
    description: "Paint directly onto 3D garments from your own files or the built-in garment library.",
    longDescription: "Layer-based painting with brush, eraser, images, text and shapes on real garment UVs. Export .ydd/.ytd with variants, .ymt and a complete add-on clothing resource.",
    icon: "Shirt",
    creditCost: 30,
    status: "live",
    requiresAuth: true,
    requiresSubscription: false,
    requiresVerification: false,
    accepts: [".ydd", ".ytd", ".zip", ".png", ".jpg"],
    outputs: [".ydd", ".ytd", ".ymt", ".meta", "fxmanifest.lua", "ZIP"],
    processor: "clothing",
    href: "/app/tools/clothing-textures",
  },
  {
    slug: "weapon-skins",
    name: "Weapon Skins",
    category: "create",
    description: "Design camo skins for 190+ vanilla weapons with UV guides and batch export.",
    longDescription: "Pick a weapon, paint on its UV template with layers, logos and text, preview in 3D, create multiple camo designs and export a single resource.",
    icon: "Crosshair",
    creditCost: 25,
    status: "live",
    requiresAuth: true,
    requiresSubscription: false,
    requiresVerification: false,
    accepts: [".png", ".jpg", ".svg"],
    outputs: ["Weapon skin resource ZIP"],
    processor: "weapon",
    href: "/app/tools/weapon-skins",
  },
  {
    slug: "tattoo-creator",
    name: "Tattoo Creator",
    category: "create",
    description: "Place tattoos on a 3D ped and export a pack with configs for your framework.",
    longDescription: "Import artwork, position it on body regions across gender variants, stack multiple tattoos, then export a tattoo pack with generated config for standalone, ESX, QBCore, Qbox, illenium-appearance and rcore.",
    icon: "Feather",
    creditCost: 25,
    status: "live",
    requiresAuth: true,
    requiresSubscription: false,
    requiresVerification: false,
    accepts: [".png", ".jpg", ".webp"],
    outputs: ["Tattoo pack", "framework configs", "ZIP"],
    processor: "tattoo",
    href: "/app/tools/tattoo-creator",
  },
  {
    slug: "face-skin-creator",
    name: "Face Skin Creator",
    category: "create",
    description: "Turn a headshot into a FiveM-compatible face texture with alignment and skin controls.",
    longDescription: "Upload a photo, let face detection align it to the head UV, tune skin tone and blending, preview on a ped head and export.",
    icon: "ScanFace",
    creditCost: 20,
    status: "live",
    requiresAuth: true,
    requiresSubscription: false,
    requiresVerification: true,
    freeDailyExports: 2,
    accepts: [".png", ".jpg", ".jpeg", ".webp"],
    outputs: ["Face texture resource ZIP"],
    processor: "face",
    href: "/app/tools/face-skin-creator",
  },
  {
    slug: "chain-creator",
    name: "Chain & Accessory Creator",
    category: "create",
    description: "Build chains, pendants, 3D lettering and accessories in a live 3D preview.",
    longDescription: "Choose a base model, customise materials, text and scale, position it on the ped and export as a wearable accessory resource.",
    icon: "Link",
    creditCost: 35,
    status: "new",
    requiresAuth: true,
    requiresSubscription: false,
    requiresVerification: false,
    accepts: [".png", ".glb"],
    outputs: ["Accessory resource ZIP"],
    processor: "accessory",
    href: "/app/tools/chain-creator",
  },
  {
    slug: "server-hub",
    name: "Server Hub",
    category: "server",
    description: "Searchable logs, private screenshots and phone media for your FiveM server.",
    longDescription: "Server-scoped bearer tokens, structured log ingestion with custom datasets, screenshot capture and one-time phone-media upload reservations backed by private object storage.",
    icon: "Server",
    creditCost: 0,
    status: "live",
    requiresAuth: true,
    requiresSubscription: false,
    requiresVerification: false,
    accepts: [],
    outputs: ["Dashboard", "API", "FiveM resource"],
    processor: "none",
    href: "/app/hub",
  },
  {
    slug: "resource-optimizer",
    name: "Resource Optimizer",
    category: "optimize",
    description: "Analyze any resource for VRAM cost, oversized textures and missing LODs — then fix it.",
    longDescription: "Expanded texture memory is not ZIP size. The optimizer measures real graphics memory, flags oversized or mip-less textures and missing LODs, and can emit an optimized resource.",
    icon: "Gauge",
    creditCost: 20,
    status: "live",
    requiresAuth: true,
    requiresSubscription: false,
    requiresVerification: false,
    accepts: [".zip"],
    outputs: ["Report", "Optimized resource ZIP"],
    processor: "optimizer",
    href: "/app/tools/resource-optimizer",
  },
  {
    slug: "vehicle-optimizer",
    name: "Vehicle Optimizer",
    category: "optimize",
    description: "Cut vehicle VRAM by fixing 4K textures, mipmaps and LODs without touching geometry.",
    longDescription: "Detects unnecessary 4K textures, unused detail, missing or poor LODs and excessive memory, and applies safe texture optimization only.",
    icon: "CarFront",
    creditCost: 20,
    status: "live",
    requiresAuth: true,
    requiresSubscription: false,
    requiresVerification: false,
    accepts: [".zip"],
    outputs: ["Report", "Optimized vehicle ZIP"],
    processor: "optimizer",
    href: "/app/tools/vehicle-optimizer",
  },
  {
    slug: "map-optimizer",
    name: "Map / MLO Optimizer",
    category: "optimize",
    description: "Find oversized textures, unused assets and LOD issues in MLO and map resources.",
    longDescription: "Analyzes interiors and maps for texture usage, oversized assets, unused files and LOD problems, then optionally generates an optimized resource.",
    icon: "Map",
    creditCost: 25,
    status: "live",
    requiresAuth: true,
    requiresSubscription: false,
    requiresVerification: false,
    accepts: [".zip"],
    outputs: ["Report", "Optimized map ZIP"],
    processor: "optimizer",
    href: "/app/tools/map-optimizer",
  },
];

export const TOOL_CATEGORIES: { key: ToolCategory; label: string; blurb: string }[] = [
  { key: "create", label: "Create & Edit", blurb: "Props, vehicles, liveries, clothing, weapons, tattoos and faces." },
  { key: "server", label: "Server Management", blurb: "Logs, screenshots and phone media for your server." },
  { key: "optimize", label: "Optimization", blurb: "Measure real VRAM cost and fix it." },
];

export const TOOL_BY_SLUG: Record<string, ToolDefinition> = Object.fromEntries(TOOLS.map((t) => [t.slug, t]));

export function getTool(slug: string): ToolDefinition | undefined {
  return TOOL_BY_SLUG[slug];
}
