import path from "node:path";
import { writeFile } from "node:fs/promises";
import type { AssetInput, AssetProcessor, CostEstimate, ProcessingJob, ProcessingResult, ProcessorContext, ValidationResult } from "@modsmith/core";
import { accessoryConfigSchema } from "@modsmith/core";
import type { WorkerReporter } from "../lib/context";
import { ProcessingError } from "../lib/errors";
import { chainMesh, lettering, MATERIAL_COLORS, pendant } from "../lib/geometry";
import { buildGlb } from "../lib/gltf";
import { computeBounds, mat4Compose, transformMesh, triangleCount, type MaterialData, type MeshData } from "../lib/mesh";
import { renderMeshThumbnail } from "../lib/thumbnail";
import { buildPropResource } from "./prop";

const WEAR_SCRIPT = (resource: string) => `-- ${resource} wearable chain (generated by Modsmith)
local model = \`${resource}\`
local attached = nil

local function wear()
    RequestModel(model)
    local timeout = GetGameTimer() + 10000
    while not HasModelLoaded(model) and GetGameTimer() < timeout do Wait(10) end
    if not HasModelLoaded(model) then
        print('[${resource}] model failed to load — is the resource streamed?')
        return
    end
    local ped = PlayerPedId()
    if attached and DoesEntityExist(attached) then DeleteEntity(attached) end
    local coords = GetEntityCoords(ped)
    attached = CreateObject(model, coords.x, coords.y, coords.z, true, true, false)
    -- 24818 = SKEL_Neck_1: the chain hangs from the neck bone.
    local bone = GetPedBoneIndex(ped, 24818)
    AttachEntityToEntity(attached, ped, bone, 0.0, -0.02, 0.0, 0.0, 0.0, 0.0, true, true, false, true, 1, true)
    SetModelAsNoLongerNeeded(model)
end

local function remove()
    if attached and DoesEntityExist(attached) then DeleteEntity(attached) end
    attached = nil
end

exports('wear', wear)
exports('remove', remove)

RegisterCommand('wearchain', wear, false)
RegisterCommand('removechain', remove, false)

AddEventHandler('onResourceStop', function(resource)
    if resource == GetCurrentResourceName() then remove() end
end)
`;

/** Build the chain/pendant/lettering geometry for a configuration. */
export function buildAccessoryMeshes(config: ReturnType<typeof accessoryConfigSchema.parse>): { meshes: MeshData[]; materials: MaterialData[] } {
  const materialName = `chain_${config.material.replace("-", "_")}`;
  const meshes: MeshData[] = [];
  const halfWidth = 0.09 * config.scale;
  const sag = 0.06 * config.scale;

  if (config.baseModel === "lettering") {
    if (!config.text?.trim()) throw new ProcessingError("MISSING_TEXT", "Enter the text for your lettering chain (up to 12 characters).");
    meshes.push(chainMesh({ style: "rope-chain", halfWidth, sag, material: materialName }));
    const letters = lettering({ text: config.text, height: 0.035 * config.scale, depth: 0.007 * config.scale });
    meshes.push({ ...transformMesh(letters, mat4Compose([0, -sag - 0.025 * config.scale, 0], [0, 0, 0], [1, 1, 1])), material: materialName });
  } else if (config.baseModel === "pendant-round" || config.baseModel === "pendant-plate") {
    meshes.push(chainMesh({ style: "cuban-chain", halfWidth, sag, material: materialName }));
    const kind = config.baseModel === "pendant-round" ? "round" : "plate";
    meshes.push({ ...pendant(kind, 0.035 * config.scale, [0, -sag - 0.03 * config.scale, 0], materialName), material: materialName });
  } else {
    meshes.push(chainMesh({ style: config.baseModel, halfWidth, sag, material: materialName }));
  }

  const preset = MATERIAL_COLORS[config.material] ?? MATERIAL_COLORS.gold!;
  const hex = preset.color.replace("#", "");
  const materials: MaterialData[] = [
    {
      name: materialName,
      baseColor: [parseInt(hex.slice(0, 2), 16) / 255, parseInt(hex.slice(2, 4), 16) / 255, parseInt(hex.slice(4, 6), 16) / 255, 1],
      metallic: preset.metallic,
      roughness: preset.roughness,
    },
  ];
  for (const m of meshes) m.material = materialName;
  return { meshes, materials };
}

export const accessoryProcessor: AssetProcessor = {
  name: "accessory",

  async validate(input: AssetInput): Promise<ValidationResult> {
    const issues: ValidationResult["issues"] = [];
    const parsed = accessoryConfigSchema.safeParse(input.config);
    if (!parsed.success) {
      issues.push({ code: "VALIDATION_ERROR", message: parsed.error.issues[0]?.message ?? "Invalid chain configuration", severity: "error" });
      return { ok: false, issues };
    }
    if (parsed.data.baseModel === "lettering" && !parsed.data.text?.trim()) {
      issues.push({ code: "MISSING_TEXT", message: "Enter the text for your lettering chain.", severity: "error" });
    }
    return { ok: !issues.some((i) => i.severity === "error"), issues };
  },

  async process(job: ProcessingJob): Promise<ProcessingResult> {
    const reporter = job.reporter as WorkerReporter;
    const config = accessoryConfigSchema.parse(job.input.config);
    const resource = config.resourceName;

    await reporter.stage("importing", 15, "Generating the chain");
    const { meshes: raw, materials } = buildAccessoryMeshes(config);
    const matrix = mat4Compose(config.position, [0, 0, 0], [1, 1, 1]);
    const meshes = raw.map((m) => transformMesh(m, matrix));
    await reporter.log(`Generated ${triangleCount(meshes)} triangles for ${config.baseModel} (${config.material})`);
    reporter.assertNotCancelled();

    const built = await buildPropResource({
      propName: resource,
      meshes,
      materials,
      config: {
        collision: "box",
        lods: { auto: true, high: 1, medium: 0.6, low: 0.3, veryLow: 0.12, distances: [25, 50, 100, 200] },
        decimation: 1,
        targetTriangles: undefined,
        spawnScript: false,
        attribution: undefined,
      },
      workDir: job.workDir,
      reporter,
      clientScripts: [{ path: "client/wear.lua", content: WEAR_SCRIPT(resource) }],
      extraReadme: {
        notes: [
          `Style: ${config.baseModel}`,
          `Material: ${config.material}`,
          ...(config.text ? [`Text: ${config.text}`] : []),
          "Attach it to a ped with `exports['" + resource + "']:wear()` or `/wearchain`; remove with `/removechain`.",
          "For a proper ped_prop (wearable through a clothing menu) the drawable must be added to the ped prop dictionary — the attach script covers the standalone case without touching game files.",
        ],
      },
    });

    const zipPath = path.join(job.workDir, `${resource}.zip`);
    await built.builder.writeZip(zipPath);

    let thumbnailPath: string | undefined;
    const png = await renderMeshThumbnail(built.lodMeshes, { yaw: 20, pitch: 10 }).catch(() => null);
    if (png) {
      thumbnailPath = path.join(job.workDir, "thumbnail.png");
      await writeFile(thumbnailPath, png);
    }
    const previewPath = path.join(job.workDir, "preview.glb");
    await writeFile(previewPath, await buildGlb(built.lodMeshes, materials, { name: resource }));

    await reporter.stage("complete", 99, "Done");
    const bounds = computeBounds(meshes);
    return {
      ok: true,
      artifact: {
        localPath: zipPath,
        fileName: `${resource}.zip`,
        mime: "application/zip",
        thumbnailPath,
        previewPath,
        manifest: {
          files: built.builder.files,
          stats: { ...built.stats, style: config.baseModel, material: config.material, sizeMetres: bounds.size.map((n) => Number(n.toFixed(3))) },
          encoder: built.encoder,
          warnings: built.warnings,
        },
      },
      facts: { resource, style: config.baseModel, material: config.material, text: config.text ?? null, triangles: built.stats.triangles },
    };
  },

  async estimateCost(_input: AssetInput, ctx: ProcessorContext): Promise<CostEstimate> {
    return { credits: ctx.baseCost, breakdown: [{ label: "Chain export", credits: ctx.baseCost }] };
  },
};
