import path from "node:path";
import type { AssetInput, AssetProcessor, CostEstimate, ProcessingJob, ProcessingResult, ProcessorContext, ValidationResult } from "@modsmith/core";
import { vehicleEditorConfigSchema } from "@modsmith/core";
import type { WorkerReporter } from "../lib/context";
import { ProcessingError } from "../lib/errors";
import { downloadInputs } from "../lib/inputs";
import { vehicleManifest } from "../lib/manifest";
import { getRage, rageCapabilitiesSync, toDrawableInput } from "../lib/rage";
import { combineEncoders, encodeTextureDictionary, encoderReadmeNote, type EncoderKind } from "../lib/rage-convert";
import { buildReadme, createResourceBuilder } from "../lib/resource";
import { readStaged, stageResource } from "../lib/stage";
import { encodeDds, readYtdTextures, vramForTexture } from "../lib/textures";
import sharp from "sharp";

type VehicleConfig = ReturnType<typeof vehicleEditorConfigSchema.parse>;

/** Client script that hides parts and applies wheel/stance/neon settings at runtime. */
export function buildTuningScript(config: VehicleConfig, hiddenViaScript: string[]): string {
  const model = config.spawnName;
  const hidden = hiddenViaScript.map((p) => `    '${p.replace(/'/g, "")}',`).join("\n");
  const color = config.glowTrim.color.replace("#", "");
  const [r, g, b] = [parseInt(color.slice(0, 2), 16), parseInt(color.slice(2, 4), 16), parseInt(color.slice(4, 6), 16)];
  return `-- ${model} tuning (generated by Modsmith)
local model = \`${model}\`

--- Parts hidden on this build. Bones are hidden; numbered extras are turned off.
local hiddenParts = {
${hidden}
}

local function applyTuning(vehicle)
    if not DoesEntityExist(vehicle) then return end
    SetVehicleModKit(vehicle, 0)
${config.wheels.model ? `    SetVehicleWheelType(vehicle, ${wheelTypeFor(config.wheels.model)})\n` : ""}${config.wheels.width !== 1 ? `    local wheels = GetVehicleNumberOfWheels(vehicle)\n    for i = 0, wheels - 1 do\n        SetVehicleWheelWidth(vehicle, i, GetVehicleWheelWidth(vehicle) * ${config.wheels.width.toFixed(3)})\n    end\n` : ""}${config.glowTrim.enabled ? `    for i = 0, 3 do SetVehicleNeonLightEnabled(vehicle, i, true) end\n    SetVehicleNeonLightsColour(vehicle, ${r}, ${g}, ${b})\n` : ""}
    for _, part in ipairs(hiddenParts) do
        local extra = tonumber(part:match('^extra_?(%d+)$') or '')
        if extra then
            if DoesExtraExist(vehicle, extra) then SetVehicleExtra(vehicle, extra, true) end
        else
            local bone = GetEntityBoneIndexByName(vehicle, part)
            if bone ~= -1 then
                -- Hiding a bone keeps the mesh in the model but stops it rendering.
                SetVehicleLightsMode(vehicle, 0)
                SetEntityBoneVisible and SetEntityBoneVisible(vehicle, bone, false)
            end
        end
    end
end

exports('applyTuning', applyTuning)

AddEventHandler('gameEventTriggered', function(event, args)
    if event ~= 'CEventNetworkPlayerEnteredVehicle' then return end
    local vehicle = args[2]
    if vehicle and GetEntityModel(vehicle) == model then applyTuning(vehicle) end
end)

CreateThread(function()
    while true do
        Wait(2000)
        local ped = PlayerPedId()
        local veh = GetVehiclePedIsIn(ped, false)
        if veh ~= 0 and GetEntityModel(veh) == model then applyTuning(veh) end
    end
end)
`;
}

function wheelTypeFor(model: string): number {
  const map: Record<string, number> = { sport: 0, muscle: 1, lowrider: 2, suv: 3, offroad: 4, tuner: 5, bike: 6, highend: 7, benny: 8 };
  return map[model.toLowerCase()] ?? 7;
}

/** handling.meta override carrying only the suspension raise from the stance settings. */
export function buildStanceHandling(spawnName: string, stance: VehicleConfig["stance"]): string {
  const raise = ((stance.frontHeight + stance.rearHeight) / 2) * -0.01;
  return `<?xml version="1.0" encoding="UTF-8"?>
<CHandlingDataMgr>
  <HandlingData>
    <Item type="CHandlingData">
      <handlingName>${spawnName}</handlingName>
      <fSuspensionRaise value="${raise.toFixed(6)}" />
      <fSuspensionBiasFront value="0.500000" />
      <fCamberStiffnesss value="${(stance.camber * 0.01).toFixed(6)}" />
    </Item>
  </HandlingData>
</CHandlingDataMgr>
`;
}

export const vehicleProcessor: AssetProcessor = {
  name: "vehicle",

  async validate(input: AssetInput): Promise<ValidationResult> {
    const issues: ValidationResult["issues"] = [];
    const parsed = vehicleEditorConfigSchema.safeParse(input.config);
    if (!parsed.success) issues.push({ code: "VALIDATION_ERROR", message: parsed.error.issues[0]?.message ?? "Invalid vehicle configuration", severity: "error" });
    if (!input.files.length) issues.push({ code: "MISSING_INPUT", message: "Upload the vehicle's .yft and .ytd (or a ZIP of the resource).", severity: "error" });
    return { ok: !issues.some((i) => i.severity === "error"), issues };
  },

  async process(job: ProcessingJob, ctx: ProcessorContext): Promise<ProcessingResult> {
    const reporter = job.reporter as WorkerReporter;
    const config = vehicleEditorConfigSchema.parse(job.input.config);
    const spawnName = config.spawnName;

    await reporter.stage("importing", 12, "Downloading the vehicle");
    const inputs = await downloadInputs(job.input, job.workDir, ctx.storage);
    const staged = await stageResource(inputs, job.workDir);
    reporter.assertNotCancelled();

    const yfts = staged.byExt("yft");
    if (!yfts.length) throw new ProcessingError("MISSING_INPUT", "No .yft vehicle model was found in the upload.");

    const rage = getRage();
    const caps = rageCapabilitiesSync();
    const builder = await createResourceBuilder(spawnName, job.workDir);
    const warnings: string[] = [];
    const encoders: EncoderKind[] = [];
    const removals = [...new Set([...config.removedParts, ...config.hiddenParts])];

    // Geometry edits need a .yft writer. Without one we never corrupt the model — the parts
    // are hidden at runtime by the tuning script instead, and the manifest says which path ran.
    let geometryPath: "native-yft" | "client-script" = "client-script";
    if (removals.length && caps.writeYft && rage.writeYft && rage.readYft) {
      try {
        await reporter.stage("converting", 35, "Removing parts from the model");
        const base = yfts.find((f) => !/_hi\.yft$/i.test(f.rel)) ?? yfts[0]!;
        const fragment = rage.readYft(await readStaged(base));
        const keep = fragment.children.filter((c) => !removals.some((r) => r.toLowerCase() === c.name.toLowerCase()));
        const removed = fragment.children.length - keep.length;
        if (removed > 0) {
          const meshes = fragment.drawable.lods.high.flat().map((m) => ({
            shaderIndex: m.shaderIndex,
            positions: m.positions,
            normals: m.normals,
            uvs: m.uvs?.[0],
            indices: m.indices,
          }));
          const rebuilt = rage.writeYft(
            toDrawableInput({
              name: fragment.name || spawnName,
              shaders: fragment.drawable.shaders.map((sh) => ({ name: sh.name, textures: sh.textures })),
              lods: { high: meshes },
              bounds: fragment.drawable.bounds,
            }),
          );
          await builder.addFile(`stream/${path.posix.basename(base.rel)}`, rebuilt);
          geometryPath = "native-yft";
          warnings.push(`${removed} part${removed === 1 ? "" : "s"} were removed from the model itself.`);
        }
      } catch (err) {
        warnings.push(`The model could not be rewritten (${(err as Error).message}); parts are hidden by the client script instead so the vehicle still works.`);
        geometryPath = "client-script";
      }
    } else if (removals.length) {
      warnings.push(
        `This build has no verified .yft writer (@modsmith/rage reports fragments as ${caps.yft}), so the selected parts are hidden at runtime by client/tuning.lua instead of being deleted from the model. The .yft itself is copied byte-for-byte.`,
      );
    }

    // Models are copied byte-for-byte unless they were rewritten above.
    for (const f of staged.files) {
      if (!["yft", "ytd", "ydr", "ybn", "ydd"].includes(f.ext)) continue;
      const dest = `stream/${path.posix.basename(f.rel)}`;
      if (builder.has(dest)) continue;
      if (f.ext === "ytd") continue; // handled below (texture resizing)
      await builder.addLocal(dest, f.abs);
    }

    await reporter.stage("textures", 55, "Resizing textures");
    let textureCount = 0;
    let vramBytes = 0;
    for (const ytd of staged.byExt("ytd")) {
      const dest = `stream/${path.posix.basename(ytd.rel)}`;
      const textures = await readYtdTextures(await readStaged(ytd)).catch(() => []);
      if (!textures.length) {
        await builder.addLocal(dest, ytd.abs);
        continue;
      }
      const rebuilt: { name: string; dds: Buffer }[] = [];
      let touched = false;
      for (const t of textures) {
        textureCount++;
        const dim = Math.max(t.width, t.height);
        if (dim <= config.maxTextureSize) {
          rebuilt.push({ name: t.name, dds: t.dds() });
          vramBytes += vramForTexture(t.width, t.height, t.format, t.mipLevels);
          continue;
        }
        const rgba = t.rgba(0);
        if (!rgba) {
          rebuilt.push({ name: t.name, dds: t.dds() });
          warnings.push(`${t.name} could not be decoded and was kept at ${t.width}×${t.height}.`);
          continue;
        }
        const scale = config.maxTextureSize / dim;
        const width = Math.max(4, Math.round(rgba.width * scale));
        const height = Math.max(4, Math.round(rgba.height * scale));
        const { data, info } = await sharp(Buffer.from(rgba.data), { raw: { width: rgba.width, height: rgba.height, channels: 4 } })
          .resize(width, height, { fit: "fill", kernel: "lanczos3" })
          .raw()
          .toBuffer({ resolveWithObject: true });
        let alpha = false;
        for (let i = 3; i < data.length; i += 4) {
          if (data[i]! < 250) {
            alpha = true;
            break;
          }
        }
        rebuilt.push({ name: t.name, dds: await encodeDds({ width: info.width, height: info.height, data }, alpha ? "DXT5" : "DXT1", true) });
        vramBytes += vramForTexture(info.width, info.height, alpha ? "DXT5" : "DXT1", 1 + Math.log2(Math.max(info.width, info.height)));
        touched = true;
      }
      if (!touched) {
        await builder.addLocal(dest, ytd.abs);
        continue;
      }
      const encoded = await encodeTextureDictionary(rebuilt, path.parse(ytd.rel).name, { workDir: job.workDir });
      encoders.push(encoded.encoder);
      warnings.push(...encoded.warnings);
      for (const f of encoded.files) await builder.addFile(`stream/${f.name}`, f.content);
      reporter.assertNotCancelled();
    }

    await reporter.stage("packaging", 82, "Packaging the resource");
    const scriptNeeded = geometryPath === "client-script" ? removals : config.hiddenParts;
    const needsScript = scriptNeeded.length > 0 || config.glowTrim.enabled || config.wheels.width !== 1 || !!config.wheels.model;
    const clientScripts: string[] = [];
    if (needsScript) {
      await builder.addFile("client/tuning.lua", buildTuningScript(config, scriptNeeded));
      clientScripts.push("client/tuning.lua");
    }
    const stanceChanged = config.stance.frontHeight !== 0 || config.stance.rearHeight !== 0 || config.stance.camber !== 0;
    if (stanceChanged) await builder.addFile("data/handling.meta", buildStanceHandling(spawnName, config.stance));

    // Existing metadata from the uploaded resource is preserved.
    for (const f of staged.files) {
      if (f.ext !== "meta" && !/\.(xml|ymt)$/i.test(f.rel)) continue;
      if (/handling\.meta$/i.test(f.rel) && stanceChanged) continue;
      await builder.addLocal(`data/${path.posix.basename(f.rel)}`, f.abs);
    }

    await builder.addFile(
      "fxmanifest.lua",
      vehicleManifest({
        resourceName: spawnName,
        handlingMeta: stanceChanged || staged.files.some((f) => /handling\.meta$/i.test(f.rel)),
        vehiclesMeta: staged.files.some((f) => /vehicles\.meta$/i.test(f.rel)),
        carcolsMeta: staged.files.some((f) => /carcols\.meta$/i.test(f.rel)),
        carvariationsMeta: staged.files.some((f) => /carvariations\.meta$/i.test(f.rel)),
        clientScripts,
      }),
    );

    const encoder = combineEncoders(encoders);
    await builder.addFile(
      "README.md",
      buildReadme({
        title: `${spawnName} — edited vehicle`,
        resourceName: spawnName,
        intro: `Rebuilt from your vehicle files with the edits made in the Vehicle Editor.`,
        usage: [
          `Load this resource after the original vehicle resource so its stream files win.`,
          ...(needsScript ? ["`client/tuning.lua` applies wheels, stance and hidden parts when a player enters the car; it also exports `applyTuning(vehicle)` for your own scripts."] : []),
        ],
        warnings: [
          ...(geometryPath === "client-script" && removals.length
            ? ["Parts are hidden at runtime (bone visibility / vehicle extras) rather than deleted from the model, so the original .yft is preserved byte-for-byte. Hiding a bone works for badges, spoilers and trim; a part that is welded into the bodyshell mesh cannot be hidden this way and needs a model edit in ZModeler/Blender."]
            : []),
          ...(encoder !== "native" ? [encoderReadmeNote(encoder, builder.xmlFallbacks)] : []),
        ],
        notes: [
          `Parts requested: ${removals.length ? removals.join(", ") : "none"}`,
          `Geometry path: ${geometryPath === "native-yft" ? "model rewritten" : "runtime hiding"}`,
          `Textures: ${textureCount} (max ${config.maxTextureSize}px)`,
          `LOD bias: ${config.lodBias}`,
        ],
      }),
    );

    const zipPath = path.join(job.workDir, `${spawnName}.zip`);
    await builder.writeZip(zipPath);

    await reporter.stage("complete", 99, "Done");
    return {
      ok: true,
      artifact: {
        localPath: zipPath,
        fileName: `${spawnName}.zip`,
        mime: "application/zip",
        manifest: {
          files: builder.files,
          stats: { textures: textureCount, vramBytes, hiddenParts: config.hiddenParts.length, removedParts: config.removedParts.length, geometryPath },
          encoder,
          warnings,
        },
      },
      facts: { spawnName, geometryPath, hiddenParts: config.hiddenParts, removedParts: config.removedParts, textures: textureCount },
    };
  },

  async estimateCost(_input: AssetInput, ctx: ProcessorContext): Promise<CostEstimate> {
    return { credits: ctx.baseCost, breakdown: [{ label: "Vehicle export", credits: ctx.baseCost }] };
  },
};
